import type { Metadata } from "next";
import Rodape from "@/components/Rodape/Rodape";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import './globals.css'; 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
          <Cabecalho/>
            {children}
          <Rodape/>
      </body>
    </html>
  );
}
